# Generated by Django 4.2.7 on 2023-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Haircare', 'Haircare'), ('Skincare', 'Skincare'), ('Bodycare', 'Bodycare'), ('Fragrance', 'Fragrance'), ('Beauty Boxes', 'Beauty Boxes')], default='Uncategorized', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
    ]
