# Generated by Django 4.2.7 on 2023-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='article_images/')),
                ('content', models.TextField()),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Haircare', 'Haircare'), ('Skincare', 'Skincare'), ('Bodycare', 'Bodycare'), ('Fragrance', 'Fragrance'), ('Beauty Boxes', 'Beauty Boxes'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
