# Generated by Django 4.2.7 on 2023-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_article_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Haircare', 'Haircare'), ('Skincare', 'Skincare'), ('Bodycare', 'Bodycare'), ('Fragrance', 'Fragrance'), ('Beauty Boxes', 'Beauty Boxes'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
